/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * user guide available at https://docs.gradle.org/5.0/userguide/java_library_plugin.html
 */

plugins {
    // Apply the java-library plugin to add support for Java Library
    `java-library`
    `maven-publish`
    `idea`
    `eclipse`
    signing
    id("org.springframework.boot")
}

apply(plugin = "io.spring.dependency-management")

repositories {
    mavenCentral()
}

val javaVersion: String by project

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(javaVersion.toInt()))
    }
}

dependencies {
    api(project(":status-machina-core"))

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    // Spring Boot 4 / Spring Framework 7 ship native retry support in spring-core
    // (org.springframework.core.retry), so the external spring-retry dependency is no longer needed.
    compileOnly("org.springframework.boot:spring-boot-starter")
    compileOnly("org.springframework.boot:spring-boot-starter-data-jpa")
    compileOnly("jakarta.validation:jakarta.validation-api")

    // Use JUnit test framework
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testImplementation("org.junit.jupiter:junit-jupiter-engine")
    testRuntimeOnly("org.springframework.boot:spring-boot-starter")
    testRuntimeOnly("org.springframework.boot:spring-boot-starter-data-jpa")
    testRuntimeOnly("jakarta.validation:jakarta.validation-api")
    testImplementation("org.postgresql:postgresql")
    // A real (binary) PostgreSQL is launched per test context via io.zonky.test.db.postgres.embedded.EmbeddedPostgres
    // and wired as the DataSource bean (see EmbeddedPostgresTestConfig). We deliberately do NOT use Zonky's
    // Spring integration (@AutoConfigureEmbeddedDatabase), whose Liquibase support does not yet work under
    // Spring Boot 4 (see zonkyio/embedded-database-spring-test#318). Spring Boot's own Liquibase auto-config
    // builds the schema against this datasource, keeping the PostgreSQL-targeted changesets faithful.
    testImplementation("io.zonky.test:embedded-postgres:2.1.0")
    testImplementation("org.liquibase:liquibase-core")
    // Spring Boot 4 split auto-configuration into per-technology modules; LiquibaseAutoConfiguration
    // now lives in spring-boot-liquibase rather than the monolithic spring-boot-autoconfigure.
    testRuntimeOnly("org.springframework.boot:spring-boot-liquibase")
    // version managed by the Spring Boot dependencies BOM (also pulled in transitively by spring-boot-starter-test)
    testImplementation("org.assertj:assertj-core")
}


tasks.getByName("jar") {
    enabled = true
}



tasks.register<Jar>("sourcesJar") {
    archiveClassifier.set("sources")
    from(sourceSets.main.get().allJava)
}

tasks.register<Jar>("javadocJar") {
    archiveClassifier.set("javadoc")
    from(tasks.javadoc.get().destinationDir)
}


tasks.getByName("bootJar") {
    enabled = false
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}



configurations {
    compileClasspath {
        resolutionStrategy.activateDependencyLocking()
    }
}

val MAVEN_UPLOAD_USER = (project.findProperty("MAVEN_UPLOAD_USER") ?: "") as String
val MAVEN_UPLOAD_PWD = (project.findProperty("MAVEN_UPLOAD_PWD") ?: "") as String

publishing {
    repositories {
        maven {
            name = "MavenCentral"
            val releasesRepoUrl = "https://oss.sonatype.org/service/local/staging/deploy/maven2"
            val snapshotsRepoUrl = "https://oss.sonatype.org/content/repositories/snapshots"
            url = uri(if (version.toString().endsWith("SNAPSHOT")) snapshotsRepoUrl else releasesRepoUrl)
            credentials {
                username = MAVEN_UPLOAD_USER
                password = MAVEN_UPLOAD_PWD
            }
        }
    }
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
            artifact(tasks["sourcesJar"])
            artifact(tasks["javadocJar"])

            pom {
                name.set("Status Machina Spring")
                description.set("Spring integration for Status Machina, a small, simple and pragmatic state machine for resilient microservices orchestration.")
                url.set("https://github.com/entzik/status-machina")
/*
                properties.set(mapOf(
                        "myProp" to "value",
                        "prop.with.dots" to "anotherValue"
                ))
*/
                licenses {
                    license {
                        name.set("The Apache License, Version 2.0")
                        url.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
                    }
                }
                developers {
                    developer {
                        id.set("entzik")
                        name.set("Emil Kirschner")
                        email.set("entzik@gmail.com")
                    }
                }
                scm {
                    connection.set("scm:git:https://github.com/entzik/status-machina.git")
                    developerConnection.set("scm:git:https://github.com/entzik/status-machina.git")
                    url.set("https://github.com/entzik/status-machina")
                }

            }

        }
    }
}

signing {
    val PGP_SIGNING_KEY: String? by project
    val PGP_SIGNING_PASSWORD: String? by project
    useInMemoryPgpKeys(PGP_SIGNING_KEY, PGP_SIGNING_PASSWORD)
    sign(publishing.publications["mavenJava"])
}
